//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractMysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public int id_Client { get; set; }
        public string Nom { get; set; }
        public string Cognom1 { get; set; }
        public string Adreça { get; set; }
        public int CodiPostal { get; set; }
        public string Poblacio { get; set; }
        public string Provincia { get; set; }
        public Nullable<int> Telefon { get; set; }
        public Nullable<int> Fax { get; set; }
        public string E_mail { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
