//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractMysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public Nullable<int> n_Factura { get; set; }
        public int id_Client { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Descompte { get; set; }
        public Nullable<int> IVA { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
